# Generated by Django 5.1.4 on 2024-12-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_usable_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usable_password',
        ),
    ]
